- name: Installing repos
  ansible.builtin.yum:
   name: https://rpms.remirepo.net/enterprise/remi-release-8.rpm
   disable_gpg_check: true
   state: latest

- name: Enable Redis
  ansible.builtin.shell: yum module enable redis:remi-6.2 -y

- name: Installing Redis
  ansible.builtin.yum:
   name: redis
   state: installed

- name: Replace value in redis.conf file
  ansible.builtin.replace:
    path: /etc/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Start service
  ansible.builtin.systemd:
   name: redis
   state: restarted

