- name: Installing repos
  ansible.builtin.yum:
   name: https://rpms.remirepo.net/enterprise/remi-release-8.rpm
   state: latest

- name: Enable Redis
  ansible.builtin.shell: yum module enable redis:remi-6.2 -y

- name: Installing Redis
  ansible.builtin.yum:
   name: redis
   state: Installed

- name: Replace value in redis.conf file
  ansible.builtin.replace:
    path: /etc/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Start service
  ansible.builtin.systemd:
   name: Redis
   state: restarted



#echo "Downloading redis remi-release"
#yum install https://rpms.remirepo.net/enterprise/remi-release-8.rpm -y &>>${log_name}
#status_check $?
#echo -e "\e[32m enabling redis 6.2\e[0m"
#yum module enable redis:remi-6.2 -y &>>${log_name}
#status_check $?
#echo -e "\e[33mInstalling redis \e[0m"
#yum install redis -y &>>${log_name}
#status_check $?
#echo -e "\e[33mModifying the config files \e[0m"
#sed -i 's/127.0.0.1/0.0.0.0/'  /etc/redis.conf /etc/redis/redis.conf
#status_check $?
#services_restart
#status_check $?