- name: frontend
  hosts: all
  become: yes
  tasks:
    - name: Install the Nginxserver
      ansible.builtin.yum:
        name: nginx
        state: latest

    - name: Remove the old app content
      ansible.builtin.file:
        path: /usr/share/nginx/html
        state: absent

    - name: Create a directory
      ansible.builtin.file:
        path: /usr/share/nginx/html
        state: directory

    - name: Unarchive the file
      ansible.builtin.unarchive:
        src: https://roboshop-artifacts.s3.amazonaws.com/frontend.zip
        dest: /usr/share/nginx/html
        remote_src: yes

    - name: Copy the file
      ansible.builtin.copy:
        src: roboshop.conf
        dest: /etc/nginx/default.d/roboshop.conf

    - name: Start service
      ansible.builtin.systemd:
        name: nginx
        state: restarted





#echo "Downloading the frontend content"
#curl -o /tmp/${app_name}.zip https://roboshop-artifacts.s3.amazonaws.com/${app_name}.zip &>> ${log_name}
#cd /usr/share/nginx/html
#unzip /tmp/${app_name}.zip &>> ${log_name}
#status_check $?

#need to copy config file
#cp /home/centos/robo-shop/roboshop.conf /etc/nginx/default.d/ &>> ${log_name}
#echo "Starting the nginx server"
#systemctl enable nginx
#systemctl restart nginx
#status_check $?