- name: Disable Mysql
  ansible.builtin.shell: yum module disable mysql -y

- name: copy the file
  ansible.builtin.copy:
  src: mysql.repo
  dest: /etc/yum.repos.d/mysql.repo

- name: installing mysql community server
  ansible.builtin.yum:
    name: mysql-community-server
    state: installed

- name: Start service
  ansible.builtin.systemd:
    name: mysqld
    state: restarted

- name: setting a password
  ansible.builtin.shell: mysql_secure_installation --set-root-pass RoboShop@1







#source common.sh
#mysql_password=$1

#if [ -z "$mysql_password" ]; then
#echo "mysql_password is missing"
#exit 1
#fi

#app_name="mysqld"
#echo script started
#yum module disable mysql -y &>> ${log_name}
#status_check $?
#echo installing Mysql community server
#cp /home/centos/robo-shop/mysql.repo /etc/yum.repos.d/mysql.repo
#status_check $?
#yum install mysql-community-server -y &>> ${log_name}
#status_check $?
#echo enabling and satrting mysqld
#services_restart
#status_check $?
#echo secure client installation
#mysql_secure_installation --set-root-pass ${password} &>> ${log_name}
#status_check $?
#mysql -uroot -pRoboShop@1 &>> ${log_name}
