- name: Installaing golang
  ansible.builtin.yum:
    name: golang
    state: installed

- name: App Pre-requisites
  ansible.builtin.import_tasks:
    file: app_presteps.yml

- name: Installing Dependencies
  ansible.builtin.command: go mod init {{ component }}
  args:
    chdir: /app

- name: Installing Dependencies
  ansible.builtin.shell: go get
  args:
    chdir: /app

- name: Installing Dependencies
  ansible.builtin.command: go build
  args:
    chdir: /app

- name: service restart
  ansible.builtin.import_tasks:
    file: systemd_setup.yml
