- name: installing mqsql client
  ansible.builtin.yum:
    name: mysql
    state: latest

- name: loading the schema
  #ansible.builtin.shell: mysql -h mysql-dev.devopsawschinni.online -uroot -pRoboShop@1 < /app/schema/{{ component }}.sql
  ansible.builtin.shell: mysql -h {{ lookup('amazon.aws.aws_ssm', 'roboshop.{{env}}.mysql.endpoint', region='us-east-1') }} -u{{ lookup('amazon.aws.aws_ssm', 'roboshop.{{env}}.mysql.username', region='us-east-1') }} -p{{ lookup('amazon.aws.aws_ssm', 'roboshop.{{env}}.mysql.password', region='us-east-1') }} </app/schema/{{ component }}.sql







#  mysql_install()
#    {
#      echo Installing mysql
#      yum install mysql -y &>> ${log_name}
#      echo Loading the schema
#      mysql -h mysql-dev.devopsawschinni.online -uroot -p${mysql_password} < /${app_dir}/schema/${app_name}.sql &>> ${log_name}
#    }