- name: Execute the nodeJs repos
  ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash

- name: Install the nginx frontend server
  ansible.builtin.yum:
   name: nodejs
   state: latest

- name: App Pre-requisites
  ansible.builtin.import_tasks:
    file: app_presteps.yml

- name: Load NodeJS Dependencies
  ansible.builtin.shell: npm install
  args:
    chdir: /app

- name: SystemD Setup
  ansible.builtin.import_tasks:
    file: systemd_setup.yml
