- name: Installing python
  ansible.builtin.yum:
    name:
           -python36
           -gcc
           -python3-devel
    state: installed


- name: App Pre-requisites
  ansible.builtin.import_tasks:
    file: app_presteps.yml


- name: Installing dependencies
  ansible.builtin.shell: pip3.6 install -r requirements.txt

- name: service restart
  ansible.builtin.import_tasks:
    file: systemd_setup.yml
